spring:
  datasource:
    #数据源配置信息
    name: pms
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://120.55.58.178:3306/study?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
    # 下面为连接池的补充设置
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 1
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 10000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true

mybatis:
  configuration:
    #全局激活mybatis缓存
    cacheEnabled: true
    #激活延迟加载
    lazyLoadingEnabled: true
    #允许返回多结果集
    multipleResultSetsEnabled: true
    #允许使用列的标号
    useColumnLabel: true
    #不允许使用JDBC的生成主键机制
    useGeneratedKeys: false
    #允许自动映射不嵌套的结果集到field
    autoMappingBehavior: PARTIAL
    #碰到未知的列时输出警告信息
    autoMappingUnknownColumnBehavior: WARNING
    #使用支持PS的executor
    defaultExecutorType: REUSE
    #等待数据库返回的过期时间
    defaultStatementTimeout: 25
    #数据库一个结果集返回的大小
    defaultFetchSize: 100
    #嵌套的SQL中不允许使用RowBouds
    safeRowBoundsEnabled: false
    #将数据库的下划线列映射到java的驼峰命名属性
    mapUnderscoreToCamelCase: true
    #一次seesion中的执行内容会被缓存
    localCacheScope: SESSION
    #当参数中没有指定JDBC类型时，指定下面的值作为数据库NULL值的JDBC类型
    jdbcTypeForNull: OTHER
    #指定哪些方法触发数据库的延迟加载
    lazyLoadTriggerMethods: equals,clone,hashCode,toString