server:
  port: 8001
spring:
  redis:
    port: 6379
    host: 127.0.0.1
    password:
  application:
    name: study-redis
eureka:
  instance:
    leaseExpirationDurationInSeconds: 90   #服务失效时间，默认值90秒
    leaseRenewalIntervalInSeconds: 10   #服务续约的间隔，默认为30秒
  client:
    registerWithEureka: true   #是否注册自己的信息到EurekaServer,默认为true
    fetchRegistry: false   #是否拉取其它服务的信息，默认是true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
logging:
  config: classpath:log4j2.xml
